### ISSUE TITLE
pre-commit hook does not respect `--from-ref` / `--to-ref`

### ISSUE THREAD

**Issue by KangOl** [akaihola/darker#103]
When running darker through `pre-commit`, it ignores the `--from-ref` and `--to-ref` arguments.

These 2 commands should behave the same.
```
pre-commit run darker --from-ref HEAD~1 --to-ref HEAD
darker --revision HEAD~1..HEAD
```

The pre-commit arguments are exposed via the environment variables `PRE_COMMIT_FROM_REF` and `PRE_COMMIT_TO_REF`

**Comment by akaihola** [comment]
Thanks @KangOl for your bug report! We'll definitely fix this for the next release.

Heads up @sherbie @samoylovfp @Pacu2 @CorreyL
