### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by shangxiao** [akaihola/darker#114]
Thanks for a much needed way to run black over git diffs ❤️ 

Would it be possible to please get a conda package setup and uploaded to Anaconda.org?

~Here are some instructions for creating a conda package from an existing pypi package: https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html~

Actually it may be preferable to have it contributed to conda forge instead:

- https://conda-forge.org/docs/maintainer/adding_pkgs.html#dev-contribute-pkgs 
- Some reasons why: https://conda-forge.org/docs/user/introduction.html#why-conda-forge

**Comment by akaihola** [comment]
I started work on a Conda package, and will resume at some point. It seems that it all happens on the Conda repositories side, with no changes needed in the Darker repo.

**Comment by akaihola** [comment]
My branch is [here](https://github.com/akaihola/staged-recipes/tree/darker) – I didn't yet create a pull request for it. Could you @shangxiao verify that I'm on the right tracks?

**Comment by shangxiao** [comment]
I'm not 100% familiar with all the required settings for conda-forge but my cursory look at the recipe shows you're in the right direction 👍  When you submit the pull request to staged-recipes someone from the conda-forge group will give it a proper review and approve it if all's good.

**Comment by martinRenou** [comment]
Oh I didn't see you were working on this already, I opened a PR this morning: https://github.com/conda-forge/staged-recipes/pull/14565

It seems that the installation fails on Windows though. Any idea why? Maybe running your CI on windows as well could be a good idea.

**Comment by akaihola** [comment]
@martinRenou running CI on Windows is a good idea. I don't work with Windows at all though, but I can see there are some examples and instructions in [GitHub Actions / Guides / Building and testing Python](https://docs.github.com/en/actions/guides/building-and-testing-python).

Could you create a Darker issue on GitHub for this?

**Comment by akaihola** [comment]
For the record, Windows installation issues fixed by #121, and Windows test failures in #124.

**Comment by akaihola** [comment]
Let's make sure the Conda package for 1.2.3 is built and works before closing this issue and the 1.2.3 release milestone. See conda-forge/darker-feedstock#1.

**Comment by akaihola** [comment]
I verified that `conda install -c conda-forge darker isort` does install Darker 1.2.3. And the installed version does reformat code correctly. Thanks for your contribution @martinRenou!
