### ISSUE TITLE
Automatically detect the proper line ending

### ISSUE THREAD

**Issue by Pacu2** [akaihola/darker#115]
> Text files created on DOS/Windows machines have different line endings than files created on Unix/Linux. DOS uses carriage return and line feed ("\r\n") as a line ending, which Unix uses just line feed ("\n").
Source: http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html#:~:text=Text%20files%20created%20on%20DOS,(%22%5Cn%22).

Darker should not modify the line ending as it results in false-positives.

E.g.
1. Create a file on Windows
2. All line endings are equal `\r\n`
3. Modify the file with Darker
4. Every line gets modified, `\r\n` line ending is changed to `\n`
5. In git-diff it looks like every single line was modified

Black on the other hand tries to check for the proper line ending
`newline = "\r\n" if b"\r\n" == lines[0][-2:] else "\n"`

**Comment by Pacu2** [comment]
@akaihola I think I can handle this somewhere during the week

**Comment by akaihola** [comment]
@Pacu2, I thought about this a bit and figured that the file encoding should also be handled correctly. Please see #117.
