### ISSUE TITLE
[VOTE HERE BEFORE 2022-03-01] Start a support/development chat channel

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#151]
Would a chatroom for support and/or development discussions be useful for Darker?

I know some projects use [Gitter](https://gitter.im/) and others [Libera Chat](https://libera.chat/) (IRC) or [GitHub Discussions](https://docs.github.com/en/discussions). Are there other good options?

I urge Darker users and contributors to vote :+1: in the appropriate comment below to decide whether to create a chatroom and which service to use. Feel free to add comments with additional proposals as well.

The vote will close on March 1st, 2022 at 7:00 a.m. UTC.

**Comment by akaihola** [comment]
To vote for [Gitter}(https://gitter.im/), add a :+1: reaction to this comment.

**Comment by akaihola** [comment]
To vote for [Libera Chat](https://libera.chat/) IRC, add a :+1: reaction to this comment.

**Comment by akaihola** [comment]
To vote against creating a chat channel, add a :+1: reaction to this comment.

**Comment by akaihola** [comment]
To vote for [GitHub discussions](https://docs.github.com/en/discussions), add a :+1: reaction to this comment.

**Comment by akaihola** [comment]
There hasn't been too much activity in this vote. I'll close it on March 1st, 2022 at midnight UTC, and let's see then which option is leading and act accordingly.

**Comment by aniketmaurya** [comment]
I vote for Github discussions

**Comment by akaihola** [comment]
[GitHub Discussions](https://github.com/akaihola/darker/issues/151#issuecomment-869064587) won. I'll set up a channel there, see #315.
