### ISSUE TITLE
Missing `--jobs` support

### ISSUE THREAD

**Issue by overratedpro** [akaihola/darker#178]
Monitoring the resource consumption with multiple Python files staged in a pre-commit scenario, the CPU is not used very effectively, since only a single subprocess is invoked. There should be a way to parallelize the workload over separate files, utilizing all available CPU cores to achieve better performance.

**Comment by rogalski** [comment]
Let's rename this issue into "missing --jobs support"

**Comment by rogalski** [comment]
Please note that despite we initially suspected CPU bottleneck, the actual root cause is different, see #204 #205 #206

**Comment by akaihola** [comment]
If we manage to improve bisection performance and short-circuit bisection on Black failures, do you still see `--jobs` necessary? If so, can you live without it until a [1.4.0](https://github.com/akaihola/darker/milestone/11) release a few weeks later?
