### ISSUE TITLE
Add ability to exclude files like black's `extend-exclude` option

### ISSUE THREAD

**Issue by fizbin** [akaihola/darker#181]
Short version: if I exclude files from being formatted with black's `extend-exclude` option in pyproject.toml, then `darker` should also not touch those files.

Longer version:

Consider a repo with three files in it:

```
testproj $ cat pyproject.toml 
[tool.black]
line-length = 100
target-version = ['py36']
extend-exclude = '''
DontReformatMe.py  # Put generated code in files named this
'''

[tool.darker]
line-length = 100
src = [
    ".",
]
revision = "main..."
extend-exclude = '''
DontReformatMe.py  # Put generated code in files named this
'''

testproj $ cat ReformatMe.py 
import sys

if len(sys.argv) >= 2:
    if sys.argv[1] == 'cat':
        print('meow')
testproj $ cat DontReformatMe.py 
import sys

if len(sys.argv) >= 2:
    if sys.argv[1] == 'cat':
        print('kitten')
```

Now do a `git add *` and `git commit -m 'Initial commit'`, followed by `black .` and `git commit -a -m 'Reformatted with black'`.  Now imagine that the time comes to add canine support to these files, so after making this obvious changes, you run `darker` before committing.

Now look as what `git diff` says:
```
testproj dtm$ git diff
diff --git a/DontReformatMe.py b/DontReformatMe.py
index d131e58..93d0c5f 100644
--- a/DontReformatMe.py
+++ b/DontReformatMe.py
@@ -1,5 +1,7 @@
 import sys
 
 if len(sys.argv) >= 2:
-    if sys.argv[1] == 'cat':
-        print('kitten')
+    if sys.argv[1] == "cat":
+        print("kitten")
+    if sys.argv[1] == "dog":
+        print("puppy")
diff --git a/ReformatMe.py b/ReformatMe.py
index 07f3639..f5f34cc 100644
--- a/ReformatMe.py
+++ b/ReformatMe.py
@@ -3,3 +3,5 @@ import sys
 if len(sys.argv) >= 2:
     if sys.argv[1] == "cat":
         print("meow")
+    elif sys.argv[1] == "dog":
+        print("woof")
```

Behold, `darker` has gone and reformatted the file called `DontReformatMe.py`, exactly as we told `black` not to. (And indeed, `black` won't touch the file if asked to reformat everything)

**Comment by akaihola** [comment]
I believe this has already been reported in #146 and fixed in #171, and this will be included in the upcoming 1.3.0 release. Could you try installing the development version from the `master` branch and verify that it behaves correctly?

Here's how to install from `master`:
```bash
pip install git+https://github.com/akaihola/darker.git@master
```

**Comment by akaihola** [comment]
@fizbin, this feature has now been released in Black 1.3.0. Does this fulfill what you needed?

**Comment by akaihola** [comment]
I tried out @fizbin's original example using Darker 1.3.2, and it did not reformat `DontReformatMe.py`. It seems version 1.3.0 fixed this problem, so I'm closing this issue now.

**Comment by brtknr** [comment]
Hmm I cant get it to work unfortunately. I added the following into my `pyproject.toml` file:
```
[tool.black]
extend-exclude = '''
^/src/alembic/versions/*.py
src/alembic/versions/20211210_154740_679ff6652fc6_merged_initial_prod_db.py
'''
[tool.darker]
extend-exclude = '''
^/src/alembic/versions/*.py
src/alembic/versions/20211210_154740_679ff6652fc6_merged_initial_prod_db.py
'''
```

If I run `black --check`, I notice that the files get ignored but doesnt seem to be getting ignored by darker somehow.
