### ISSUE TITLE
If bisect is attempted, performance suffers

### ISSUE THREAD

**Issue by rogalski** [akaihola/darker#205]
This bug is based on my experiments with darker on closed-source repo.
I am not at liberty to disclose any code. We'll have to work on recreating failure criteria on our own.

- `run_black`, `diff_and_get_opcodes` and `opcodes_to_chunks` are run in each pass of bisect loop, despite being independent from context_lines variable: https://github.com/akaihola/darker/blob/master/src/darker/__main__.py#150
- `verify_ast_unchanged` on failure invokes quite slow dump debug logic, which should be skipped in our bisect, as we _expect_ some non-equivalent ASTs in a process
- During bisect we will be hitting cases where changing context_lines will not include new chunks in reformatted file.  I believe caching state of intermediate comparisons (e.g. reformatted file -> comparison result dict) also makes a lot of sense.

Combination of running darker over very large files (in vicinity of 20k lines) and triggering darker to go into bisect mode will expose issue.

**Comment by akaihola** [comment]
Thanks @rogalski, I really appreciate that you've taken the trouble to dive into Darker's code base!

>`run_black`, `diff_and_get_opcodes` and `opcodes_to_chunks` are run in each pass of bisect loop, despite being independent from context_lines variable: https://github.com/akaihola/darker/blob/d269159bd23391be7b0c414d550441a2438de718/src/darker/__main__.py#L150 https://github.com/akaihola/darker/blob/d269159bd23391be7b0c414d550441a2438de718/src/darker/__main__.py#L155 https://github.com/akaihola/darker/blob/d269159bd23391be7b0c414d550441a2438de718/src/darker/__main__.py#L158

This is an excellent observation and will definitely need to be fixed. Thank you!

>`verify_ast_unchanged` on failure invokes quite slow dump debug logic, which should be skipped in our bisect, as we expect some non-equivalent ASTs in a process

Are you running with debug logging? We do have
```python
def debug_dump(black_chunks: List[DiffChunk], edited_linenums: List[int]) -> None:
    """Print debug output. This is used in case of an unexpected failure."""
    if logger.getEffectiveLevel() > logging.DEBUG:
        return
    # ...
```
The default logging level is `WARNING` (30) which is "larger" than `DEBUG` (10).

>During bisect we will be hitting cases where changing `context_lines` will not include new chunks in reformatted file

Do you mean that we could check whether `edited_linenums` already contains all reformatted lines in (those covered by `black_chunks`), stop right there and conclude that Black is not able to reformat the file and keep the AST intact?

>I believe caching state of intermediate comparisons (e.g. reformatted file -> comparison result dict) also makes a lot of sense.

Wouldn't this be effectively the same as moving `run_black()`, `diff_and_get_opcodes()` and `opcodes_to_chunks()` outside and before the bisect loop?

**Comment by rogalski** [comment]
About slow debug code - I am mostly talking about `stringify_ast` in black:
https://github.com/psf/black/blob/22747a6937d53e38397e96c4ed5ed0571db31f71/src/black/__init__.py#L1220

About caching intermediate state: no, moving those calls out of the loop is not enough.
Going back to `black.assert_equivalent`:
https://github.com/psf/black/blob/22747a6937d53e38397e96c4ed5ed0571db31f71/src/black/__init__.py#L1201
- we'll call `parse_ast` for `src` repetitively, even though for single file reformatted in `darker` passed value will never change
- we'll also call method with same `dst` (when new bisect value ends up with selecting same `DiffChunk`s and one of earlier attempts)

Once again, this is not painful if we do not hit bisect or we work on small files. But if we have large file and try to bisect, burning those CPU cycles instead of doing lookups to cached in-memory values are painful.

**Comment by akaihola** [comment]
@rogalski, thanks for clarifying the parts I had misunderstood!

I've now split this issue into four separate ones for each of the potential optimizations: #210, #211, #212 and #213. Let me know if any of them still contain some misunderstandings by me.

In particular, I'm unsure about the discussion about `stringify_ast()` vs `dump_to_file()` in #211.
