### ISSUE TITLE
README and changelog improvements

### ISSUE THREAD

**Issue by Hainguyen1210** [akaihola/darker#22]
I have just found this great tool. 
Thank you so much for building this one.

The documentation helped me to integrate successfully with Pycharm, however, I cannot find a way to specify the black arguments even though it says they are supported.
Can you please update the README with an example of how to specify black arguments while running darker?

Thanks in advance.

**Comment by akaihola** [comment]
Hi @Hainguyen1210,

Thanks for your report!

We've been adding a few new features in the past weeks, among them support for some Black arguments. The `README` you see at https://github.com/akaihola/darker reflects what is currently in the `master` branch. The [PyPI project page](https://pypi.org/project/darker/) shows the `README` for the latest release.

The [0.2.0 release](https://github.com/akaihola/darker/tree/0.2.0) didn't yet support the `--config`, `--skip-string-normalization` and `--line-length` arguments, so if you did a `pip install darker`, those won't work.

If you *have* installed from `master`, you'll just need to add any arguments you want in the `Arguments` field of the PyCharm external tool configuration, e.g. `"-S -l 120 $FilePath$"`.

I can see a couple of easy improvements we could make to [README.rst](https://github.com/akaihola/darker/blob/master/README.rst):
- point out whether the `README` is for a release or a development version
- link to the `README` of the latest release (maybe just link to [PyPI](https://pypi.org/project/darker/) so we don't need to keep updating the link)
- link to the [change log](https://github.com/akaihola/darker/blob/master/CHANGES.rst)
- add some arguments to the PyCharm external tool example

Also in [CHANGES.rst](https://github.com/akaihola/darker/blob/master/CHANGES.rst) we could
- under the development version heading (`0.3.0.dev / yyyy-mm-dd`), explain that those features aren't yet in a release
- link to each release [listed on PyPI](https://pypi.org/project/darker/#history) and possibly the corresponding [tags on GitHub](https://github.com/akaihola/darker/tags)

I'll work on those, but can you think of other changes which would make the new user experience better?

**Comment by Hainguyen1210** [comment]
Thank you so much for the explanation in detail.

Yes, I agree that those changes are needed and that should make it much clearer for the new users.
I also want to suggest that just a little change might help. [Here](https://github.com/akaihola/darker#black-command-line-arguments) you can just say that `black command line arguments that are supported from version 0.3.0.dev`.

That is my personal opinion, I am looking for the upcomming great features!
Thank you so much and have a nice day to all of you!

**Comment by akaihola** [comment]
I suggested to:
>- point out whether the `README` is for a release or a development version

How do we make sure that such a note in `README.rst` is omitted whenever we upload a release to PyPI?

Apart from an ugly `setup.py` hack which I tried and tested, I can't think of an automated way.

Any ideas @DylanYoung / @CorreyL / @Mystic-Mirage / @Carreau?

**Comment by Mystic-Mirage** [comment]
I don't think it's a good idea to add a note about active development to the development branch. Black doesn't have it.

People should understand that if they come to the development area there are a lot of things that could still be in development.

The only thing I rather changing is to replace `0.3.0.dev / yyyy-mm-dd` to `Unreleased` in [CHANGES.rst](/akaihola/darker/blob/dcb6d3a3afa37c0f3d8da7b8ce3212c766f736f7/CHANGES.rst)

**Comment by DylanYoung** [comment]
I don't think there's a really nice way to do this.  Best I can think of for fully automatic off the top is to move the `long_description` into `setup.py` and trim off the warning before passing it to setup. 

I agree that changing the version in CHANGES.rst would help. 

The other option is to make it a part of the release process (bump version number, remove note from README, etc...).  A simple script could be used to automate that...

**Comment by Carreau** [comment]
Yeah, on GitHub there is not much that can be done. On readthedocs you can do conditional RST compilations.

I think that it is a relative expectation that readme on GitHub covers master and not the latest release.

I still need to document how to set the --diff flag for VS Code.

**Comment by DylanYoung** [comment]
@Carreau Curious.  What do you use the `--diff` flag for in vscode?

**Comment by akaihola** [comment]
@Carreau wrote:
>I think that it is a relative expectation that readme on GitHub covers master and not the latest release.

Agreed. And it actually already helps if each feature includes a note about in which version it was introduced (which is something I intend to add).

**Comment by akaihola** [comment]
@Carreau wrote:
>I still need to document how to set the --diff flag for VS Code.

Feel free to add a commit in #25.
