### ISSUE TITLE
Read black settings from pyproject.toml

### ISSUE THREAD

**Issue by DylanYoung** [akaihola/darker#24]
Just banging my head against this with vscode, so thought I'd check the source.  

Correct me if I'm wrong but pyproject.toml isn't currently supported here, right?

It'd be a nice enhancement if it were, but if not, it'd be nice to note in the docs that it doesn't work.

**Comment by akaihola** [comment]
Support for `pyproject.toml` is coming in the next release. You can try it out by installing `darker` from the `master` branch.

**Comment by DylanYoung** [comment]
I wasn't sure if that included the auto-detection or just the command line flags.   I thought I still had to pass the flags in my editor, but perhaps I fudged up my testing.

**Comment by DylanYoung** [comment]
I can see that the unittest is checking this case though (looks like it is anyways).  Thanks @akaihola!  I wonder if an update to the changelog to mention that auto-detection is working as well is worthwhile?   If you think so, I can modify this issue to reflect that instead.   Otherwise, you can close it :)

**Comment by akaihola** [comment]
@DylanYoung I'm all for mentioning the auto-detection in the changelog, go ahead!

Also, I believe it isn't described in the documentation either. That could still be addressed in #22.

**Comment by akaihola** [comment]
@DylanYoung, do the additions to the `README` in 422996b match with what you had in mind?

**Comment by DylanYoung** [comment]
Absolutely! Closed by 422996b and PR #1
