### ISSUE TITLE
No support for using `flynt` to convert old string literal formatting to f-strings

### ISSUE THREAD

**Issue by jedie** [akaihola/darker#266]
https://github.com/ikamensh/flynt is a great tool. Think it's nice if darker includes this.

**Comment by akaihola** [comment]
Great idea! It would be a good addition to Black and isort. Let's see how it fits in – it was a bit tricky to get isort in since it can change the order of lines, but that shouldn't be an issue here. It's more that we should be careful about in which order different tools are applied.
