### ISSUE TITLE
exclude files/directories, how?

### ISSUE THREAD

**Issue by jedie** [akaihola/darker#273]
black normal respects .gitignore it seems that with darker this is not the case, isn't it?

How to exclude files?

**Comment by akaihola** [comment]
In #171 and #215 we added some support for respecting Black exclusions. But apparently `.gitignore` was missed there?!?

Thanks for the report, I'll try to reproduce, and this needs to be fixed for sure.

**Comment by akaihola** [comment]
Ok, I can't reproduce this on Darker 1.3.2. If I create the file `./src/ignored_file.py` in a Git repository with these contents:
```python
a = 2
b  =  5
```
and run `darker --diff src`, I get
```diff
--- darker/ignored_file.py	2022-02-06 17:30:51.041694 +0000
+++ darker/ignored_file.py	2022-02-06 17:31:14.314713 +0000
@@ -1,2 +1,2 @@
 a = 2
-b  =  5
+b = 5
```

If I then add `ignored_file.py` to `./.gitignore` and run `darker --diff src` again, I don't get any output.

Does this differ from the behavior on your system @jedie?
