### ISSUE TITLE
pytest-flake8 deprecation warning from Pytest

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#285]
In [recent test builds](https://github.com/akaihola/darker/runs/5169472289?check_suite_focus=true) we have:
```python
_pytest/nodes.py:146: 43 warnings
  _pytest/nodes.py:146: PytestDeprecationWarning: <class 'pytest_flake8.Flake8Item'> is not using a cooperative constructor and only takes {'fspath', 'parent'}.
  See https://docs.pytest.org/en/stable/deprecations.html#constructors-of-custom-pytest-node-subclasses-should-take-kwargs for more details.
    warnings.warn(

_pytest/nodes.py:672: 43 warnings
  _pytest/nodes.py:672: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to Flake8Item is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    super().__init__(

_pytest/nodes.py:708
  _pytest/nodes.py:708: PytestWarning: Flake8Item is an Item subclass and should not be a collector, however its bases File are collectors.
  Please split the Collectors and the Item into separate node types.
  Pytest Doc example: https://docs.pytest.org/en/latest/example/nonpython.html
  example pull request on a plugin: https://github.com/asmeurer/pytest-flakes/pull/40/
    warnings.warn(
```

Maybe there's an update to `pytest-flake8` which updates this behavior and silences the warning?

**Comment by RishiKumarRay** [comment]
It is happening with pytest = 7.0.0 update

**Comment by RishiKumarRay** [comment]
@akaihola i totally agree with you we can wait as its just a warning

**Comment by akaihola** [comment]
But since we do need to fix the same problem in akaihola/pytest-darker#7, we'll probably learn how to fix `pytest-flake8` as well.

**Comment by akaihola** [comment]
Moving this to milestone 1.5.0, there are a plenty of bugfixes and documentation improvements coming up for a 1.4.2 bugfix release already.

**Comment by akaihola** [comment]
In [tholo/pytest-flake8#83](https://github.com/tholo/pytest-flake8/issues/83#issuecomment-1030503256), @jaraco mentions:
>See jaraco/pytest-checkdocs#9 and jaraco/pytest-perf#5 for approaches I used to fix this issue.

He also writes:
>See pytest-dev/pytest#8435 for background

I guess I'll take a look at those and copy his solution to akaihola/pytest-darker#7 and maybe try to contribute it to tholo/pytest-flake8#83 as well.

**Comment by akaihola** [comment]
With `pytest-flake8==1.1.0` and `pytest==7.0.0` I used to get these:
```
_pytest/nodes.py:146
  _pytest/nodes.py:146: PytestDeprecationWarning: <class 'pytest_flake8.Flake8Item'> is not using a cooperative constructor and only takes {'fspath', 'parent'}.
  See https://docs.pytest.org/en/stable/deprecations.html#constructors-of-custom-pytest-node-subclasses-should-take-kwargs for more details.
    warnings.warn(

_pytest/nodes.py:686
  _pytest/nodes.py:686: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to Flake8Item is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    super().__init__(
```

After upgrading to `pytest==7.1.1`, I additionally see this one:
```
_pytest/nodes.py:708
  _pytest/nodes.py:708: PytestWarning: Flake8Item is an Item subclass and should not be a collector, however its bases File are collectors.
  Please split the Collectors and the Item into separate node types.
  Pytest Doc example: https://docs.pytest.org/en/latest/example/nonpython.html
  example pull request on a plugin: https://github.com/asmeurer/pytest-flakes/pull/40/
    warnings.warn(
```

But after upgrading to `pytest-flake8==1.1.1` they all disappear.

But tholo/pytest-flake8#83 is still `Open` – was the fix applied in some other PR?

**Comment by akaihola** [comment]
In #361 we're changing the CI setup so Flake8 is run directly in its own workflow instead of through the Pytest plugin. That should make it unnecessary to address this issue. So we could close this issue, right @RishiKumarRay?
