### ISSUE TITLE
Add support for the `NO_COLOR` environment variable

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#355]
pypa/pip#10909 is so far the "highest profile" discussion I've found on this topic.

It seems that [pip](https://github.com/pypa/pip) and [colorama](https://github.com/tartley/colorama) are going to support only `FORCE_COLOR=<anything>` and `NO_COLOR=<anything>`, but not `PY_COLORS`.

On the other hand, Pytest does support `PY_COLORS={1|0}` and `NO_COLOR=<anything>` (with `PY_COLORS` taking precedence).

So in the end it may be best to do the same as Pytest:
- `PY_COLORS={1|0}` (taking precedence over other options)
- `NO_COLOR=<anything>`
- and possibly `FORCE_COLOR=<anything>` (similar to [pip](https://github.com/pypa/pip) and [colorama](https://github.com/tartley/colorama))

As for the `true`/`false` discussion, I'm going to make the call to only support `PY_COLORS={0|1}` for now. Thanks @MatthijsBurgh for initiating the discussion and motivating me to look further into the topic!

_Originally posted by @akaihola in https://github.com/akaihola/darker/pull/353#discussion_r846752942_

**Comment by MatthijsBurgh** [comment]
Good job. I can only agree with the suggestion. So you want to keep #353 to only support the `PY_COLORS` and implement the suggested behavior in a new PR?

**Comment by akaihola** [comment]
>keep https://github.com/akaihola/darker/pull/353 to only support the PY_COLORS and implement the suggested behavior in a new PR?

Yes @MatthijsBurgh I think I'd like to have these in separate issues.

The other question then is whether to
- release [1.5.0](https://github.com/akaihola/darker/milestone/13) without #355,
- move both #353 and #355 into e.g. the [1.5.1](https://github.com/akaihola/darker/milestone/15) release
- delay the [1.5.0](https://github.com/akaihola/darker/milestone/13) release and include both `PY_COLORS` and `NO_COLOR` in it

**Comment by MatthijsBurgh** [comment]
I think option 2/3 is the best one. I think both should be included in the same release. And I think the version should be a minor version bump. So it will be 1.5.0 or 1.6.0 depending on whether you want to wait for this feature or release a version without it for now.
