### ISSUE TITLE
GH Action error

### ISSUE THREAD

**Issue by MatthijsBurgh** [akaihola/darker#362]
**Describe the bug**
```py
argument PATH: Error: Path(s) '.' do not exist in 09237df1dd54d667598bf82b432a74f621f3d052
```

**To Reproduce**
Just running GH actions with the following options: ``
Which result in the following environment variables:
env:
    INPUT_OPTIONS: --check --diff -l 120
    INPUT_SRC: .
    INPUT_VERSION: 1.5.0
    INPUT_REVISION: 
    INPUT_LINT: 
    INPUT_COMMIT_RANGE: b2e1bfe99aa6c9e149ba6453a77770547bab4180...09237df1dd54d667598bf82b432a74f621f3d052
    pythonioencoding: utf-8

**Expected behavior**
No error 😉 

**Screenshots**
https://github.com/MatthijsBurgh/epydoc/runs/6154261435?check_suite_focus=true#step:3:90

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Python version 3.8.10
 - Git version 2.35.1
 - Darker version 1.5.0
 - Black version 22.3.0

**Additional context**
I think the problem is the `INPUT_SRC` path. Only indication for that is the matching dot.
_update_: I have no idea why it says it can't find the dot in the latest commit hash.
_update2_: Error is comming from https://github.com/akaihola/darker/blob/ad6cde1ba0f8d01e658ba2d023c8412af6219fdb/src/darker/__main__.py#L415-L422

**Comment by akaihola** [comment]
I think we need to handle the repository root specially (i.e. always `True`):
```python
>>> from pathlib import Path
>>> from darker.git import _git_exists_in_revision
>>> _git_exists_in_revision(Path("."), "HEAD", Path.cwd())
False
>>> _git_exists_in_revision(Path("src"), "HEAD", Path.cwd())
True
```
