### ISSUE TITLE
Incompatible with `black-22.10.1.dev19+gffaaf48` and later

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#403]
**Describe the bug**
Unit tests fail if psf/black@ffaaf48 or later is installed.

**To Reproduce**
1. In a fresh virtualenv, `pip install 'darker[test]==1.5.1' git+https://github.com/psf/black.git@ffaaf48`
2. In a Git working tree of a Python repository, run Darker with `darker`
3. See error

**Expected behavior**
Darker should run successfully and reformat modified regions of Python fules.

**Screenshots**
```python
Traceback (most recent call last):
  File "bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "darker/__main__.py", line 486, in main_with_error_handling
    return main()
  File "darker/__main__.py", line 423, in main
    files_to_process = filter_python_files(paths, root, {})
  File "darker/black_diff.py", line 142, in filter_python_files
    gen_python_files(
TypeError: gen_python_files() got an unexpected keyword argument 'gitignore'
```

**Environment (please complete the following information):**
 - OS: NixOS 22.05
 - Python version: 3.9.13
 - Git version: 2.36.2
 - Darker version: 1.5.1
 - Black version: commit `ffaaf48`

**Additional context**
psf/black@ffaaf48 replaces the `gitignore: Optional[PathSpec]` argument of `black.files.gen_python_files()` with `gitignore_dict: Optional[Dict[Path, PathSpec]]`.

Before that commit, `gitignore` is used like:
```python
        # First ignore files matching .gitignore, if passed
        if gitignore is not None and gitignore.match_file(normalized_path):
            report.path_ignored(child, "matches the .gitignore file content")
            continue
```
And after the commit, `gitignore_dict` like:
```python
        # First ignore files matching .gitignore, if passed
        if gitignore_dict and path_is_ignored(child, gitignore_dict, report):
            continue

# [...]

        if child.is_dir():
            # If gitignore is None, gitignore usage is disabled, while a Falsey
            # gitignore is when the directory doesn't have a .gitignore file.
            if gitignore_dict is not None:
                new_gitignore_dict = {
                    **gitignore_dict,
                    root / child: get_gitignore(child),
                }
            else:
                new_gitignore_dict = None

# [then passing `new_gitignore_dict` back to the same function
```

**Comment by soxofaan** [comment]
An out-of-the-box pipx install of darker is also broken at the moment.

Workaround is to use [pipx inject](https://pypa.github.io/pipx/docs/#pipx-inject)  to downgrade black:

    pipx inject darker 'black<22.12.0'

**Comment by akaihola** [comment]
@soxofaan, thanks for appreciation! Darker 1.6.0 with a fix for this has now been released.
