### ISSUE TITLE
Action akaihola/darker@1.7.0 failing

### ISSUE THREAD

**Issue by roniemartinez** [akaihola/darker#467]
(the following sections were added by @akaihola, see "**Original bug report**" below for what @roniemartinez's first sent in)

### Failing steps

The equivalent of these are executed by Darker in the GitHub action:
```bash
$ git clone /home/runner/work/darker/darker /tmp/tmpxxxxxxxx/darker
$ cd /tmp/tmpxxxxxxxx/darker
$ git checkout origin/master
error: pathspec 'origin/master' did not match any file(s) known to git
```

### Planned analysis steps

- [x] repeat the problem on GitHub
  - see #469 and [Darker build #6](/akaihola/darker/actions/runs/4213081314/jobs/7312562040)
- [x] get the failing [raw log](https://github.com/akaihola/darker/commit/e9b3882174719f9ad8957236e3f96fd7ecfccea8/checks/11440672648/logs) from the build
- [ ] clone a repository locally with the steps used by `actions/checkout@v3` in the failing build
- [ ] make sure we see the same problem locally
  - `git clone <cloned-repo-path> /tmp/local-clone`
  - `cd /tmp/local-clone`
  - `git checkout origin/master`
- [ ] come up with required modifications to `git clone` and/or `git checkout` to prevent the problem

---

### Original bug report

We have the same setup for Github actions as we have with `akaihola/darker@1.6.1` but it failed after upgrading to 1.7.0. (had to revert)

```yml
      - name: Run Darker
        uses: akaihola/darker@1.6.1
        with:
          options: --check --diff --color --isort --config pyproject.toml
          revision: origin/develop...
          lint: flake8
```

Here is the error log
```python
error: pathspec 'origin/develop' did not match any file(s) known to git
Traceback (most recent call last):
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/__main__.py", line 630, in main_with_error_handling
    return main()
           ^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/__main__.py", line 611, in main
    linter_failures_on_modified_lines = run_linters(
                                        ^^^^^^^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/linting.py", line 416, in run_linters
    baseline = _get_messages_from_linters_for_baseline(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/linting.py", line 527, in _get_messages_from_linters_for_baseline
    clone_root = git_clone_local(root, revision, Path(tmp_path))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/git.py", line 498, in git_clone_local
    _ = _git_check_output(["checkout", revision], clone_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/akaihola/darker/1.7.0/.darker-env/lib/python3.11/site-packages/darker/git.py", line 341, in _git_check_output
    return check_output(  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'checkout', 'origin/develop']' returned non-zero exit status 1.
```

**Comment by akaihola** [comment]
Thanks @roniemartinez, I'll investigate what might be causing this.

Also I think it's now worth figuring out how to create an automated test for the action.

**Comment by akaihola** [comment]
Looking at the traceback, this obviously happens when the new linting mechanism tries to create a local clone of the repository at the `rev1` revision.

**Comment by akaihola** [comment]
So since `revision: origin/develop...` works with Darker 1.6.1, your checkout must have the `origin/develop` branch. Somehow `git clone --quiet <src> <dest>` fails to make that branch available in the cloned repository.

I tried this out wtih one of my existing repository clones on my laptop, and can't yet reproduce the situation.

Could you @roniemartinez show your `- uses: actions/checkout@v3` parameters (if any)?

**Comment by akaihola** [comment]
@roniemartinez I wonder whether `fetch-depth: 0` for `actions/checkout@v3` would make a difference? Or are you already using it?

**Comment by roniemartinez** [comment]
@akaihola We are already using `fetch-depth: 0`

```yml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

**Comment by akaihola** [comment]
I'm trying to reproduce this in #469. Instead of `origin/develop` (which we don't have) or `origin/master` (the default branch), I arbitrarily picked `origin/blue` as my `rev1`.

With 1.6.1, this indeed [works](/akaihola/darker/actions/runs/4212806697/jobs/7312091146) (fails with some black reformattings, but let's nevermind that).

But it seems to [work](/akaihola/darker/actions/runs/4212820336/jobs/7312114823) here with 1.7.0 as well.

What might be different in your repository?

**Comment by roniemartinez** [comment]
> What might be different in your repository

Bugs me, too.... But here is what we know:

1. Update PR (actions = 1.7.0) worked for us.
2. We merged it.
3. Succeeding PRs then started failing

Another difference is that `origin/develop` is our main branch.

**Comment by akaihola** [comment]
>We merged it.

Oh shoot, a bit difficult to test then. I'll need to create another repository.

Could you by any chance download the raw log for the failing build, remove/change any sensitive parts, and send it to me? Maybe looking at the Git commands run by `actions/checkout` and output from them could help reason about the problem.

**Comment by roniemartinez** [comment]
For completeness... here is our workflow

```yml
nam: Linter

on: pull_request

jobs:
  be-lint:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Run Darker
        uses: akaihola/darker@1.6.1
        with:
          options: --check --diff --color --isort --config pyproject.toml
          revision: origin/develop...
          lint: flake8
```

**Comment by akaihola** [comment]
Ok, changing from `origin/blue...` to `origin/master...` *did* cause you error to occur, see [build #6](/akaihola/darker/actions/runs/4213081314/jobs/7312562040).

**Comment by akaihola** [comment]
My plan is to
- use the failing build logs to replicate locally what `actions/checkout` does, and
- hope making a local clone and trying to check out `origin/master` would cause the error again.

Then we might be able to come up with a way to do the local clone and/or checkout `rev1` in a better way.

**Comment by akaihola** [comment]
These are the steps executed by `actions/checkout@v3` in Darker PR builds when using `with: fetch-depth: 0`:
```bash
git version
git config --global --add safe.directory /home/runner/work/darker/darker
git init /home/runner/work/darker/darker
git remote add origin https://github.com/akaihola/darker
git config --local gc.auto 0
git config --local --name-only --get-regexp core\.sshCommand
git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
git branch --list --remote origin/reproduce-issue-467
git rev-parse refs/remotes/origin/reproduce-issue-467
git checkout --progress --force -B reproduce-issue-467 refs/remotes/origin/reproduce-issue-467
git log -1 --format='%H'
```

**Comment by akaihola** [comment]
For the record, I remember trying to use
```bash
git clone --branch <repo>
```
instead of
```bash
git clone <repo> <copy>
cd <copy>
git checkout <branch>
```

But that didn't work under some conditions.

Actually what might be appropriate here instead of either of those approaches is [`git worktree add`](https://git-scm.com/docs/git-worktree#Documentation/git-worktree.txt-addltpathgtltcommit-ishgt).
