### ISSUE TITLE
Switch from argparse to click

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#47]
Black uses it anyway and is a dependency of Darker.

Does [click](https://pypi.org/project/click/) allow limiting arguments to only one occurrence?

[Argparse](https://docs.python.org/3/library/argparse.html) doesn't support that out of the box, so
```bash
$ myscript.py -a first -a second -a third
```
will either ignore all but `-a third`, or collect them all to a list (with `action="append"`).

**Comment by Carreau** [comment]
> Does [click](https://pypi.org/project/click/) allow limiting arguments to only one occurrence?

No, it does like argparse and `--a A --a B` will end up with `B` as the value. You can use multiple=True and check the length.

```
import click

@click.command()
@click.option('--name', nargs=1, multiple=False)
def hello(name):
    click.echo(f"Hello, {name}!")

if __name__ == '__main__':
    hello()
```

**Comment by Carreau** [comment]
I'm also not sure click will be that simpler, I find that click is useful if you have many subcommands. Not that much when you only have one with many options.

**Comment by akaihola** [comment]
I've also been quite comfortable with argparse most of the time, and happy to not bring yet another dependency into projects.

So let's postpone this change until we really need something that argparse can't do easily.
