### ISSUE TITLE
mypy fails with "baseline-revision is not a valid Python package name" in the baseline worktree if the git repo toplevel contains __init__.py

### ISSUE THREAD

**Issue by tapted** [akaihola/darker#498]
**Describe the bug**

If the top-level of a git repo has an `__init__.py` in it, then the step that does
```shell
git worktree add --quiet --force --force /tmp/tmpF00/baseline-revision HEAD
```
will create a file `baseline-revision/__init__.py`. When mypy sees this, it expects "baseline-revision" to be a valid python package name. But it's not because of the hyphen.

https://github.com/python/mypy/issues/8400 talks a bit about this issue, and there are folks asking for a way to suppress it.

But there's a simple fix in Darker, like

```diff
diff --git a/src/darker/linting.py b/src/darker/linting.py
index bc2055f..1e285d6 100644
--- a/src/darker/linting.py
+++ b/src/darker/linting.py
@@ -524,7 +524,7 @@ def _get_messages_from_linters_for_baseline(

     """
     with TemporaryDirectory() as tmpdir:
-        tmp_path = Path(tmpdir) / "baseline-revision"
+        tmp_path = Path(tmpdir) / "baseline-revision" / root.name
         with git_clone_local(root, revision, tmp_path) as clone_root:
             rev1_commit = git_rev_parse(revision, root)
             result = _get_messages_from_linters(
```

i.e., always create the worktree in a subfolder of "baseline-revision". Sharing the same name as where the repo is checked out should be most reliable. (E.g. if the project config assumes the top-level of the git repo is in PYTHONPATH).

**To Reproduce**
1. Clone this repository: 'https://chromium.googlesource.com/chromiumos/chromite'
    - (or just make a git repo with an `__init__.py` at the top level and any other)
2. Run Darker with `darker -vvv --lint --check --lint "mypy --follow-imports=silent" api/controller/sysroot.py`
3. See error / wrong behavior

"-vvv" will show the output, "baseline-revision is not a valid Python package name".

Otherwise, the effect is just to treat the baseline as having no errors, so all mypy errors on the files are emitted, without filtering.

**Expected behavior**

Just new mypy errors to be emitted.

**Tested with:**

  - darker@a7f586428f44d07795dba601fb21db0fb5ede22b (May 1 2023)
  - mypy 1.3.0
  - Python 3.10.9

**Comment by akaihola** [comment]
@tapted thanks for the report and the proposed fix, excellent!

**Comment by akaihola** [comment]
@tapted can I add you as a collaborator for this repository and assign #499 for you to review?
