### ISSUE TITLE
version specification for black makes poetry fails

### ISSUE THREAD

**Issue by CircleOnCircles** [akaihola/darker#52]
It seems like poetry doesn't understand `*` version.
 
```bash
 poetry add --dev darker
Using version ^1.0.0 for darker

Updating dependencies
Resolving dependencies...

[SolverProblemError]
Because no versions of darker match >1.0.0,<2.0.0
 and darker (1.0.0) depends on black (*), darker (>=1.0.0,<2.0.0) requires black (*).
So, because no versions of black match *
 and gebwai-backend depends on darker (^1.0.0), version solving failed.
```

**Comment by akaihola** [comment]
Hi @CircleOnCircles,

Thanks for the report!

I looked by didn't yet find out where the `*` asterisk comes from.

In darker 1.0.0 [setup.cfg](https://github.com/akaihola/darker/blob/1.0.0/setup.cfg#L26-L28) we have:
```ini
install_requires =
    black
    typing-extensions ; python_version < "3.8"
```

Looking inside [darker-1.0.0-py3-none-any.whl](https://files.pythonhosted.org/packages/09/b6/3ba825126169f2ae860a6cb19b05db23b5304f801f0ebadfceadbc0aa891/darker-1.0.0-py3-none-any.whl) on PyPI, we have:
```bash
$ unzip -p darker-1.0.0-py3-none-any.whl darker-1.0.0.dist-info/METADATA|grep Requires-Dist
Requires-Dist: black
Requires-Dist: typing-extensions ; python_version < "3.8"
Requires-Dist: isort (>=5.0.1) ; extra == 'isort'
Requires-Dist: pytest ; extra == 'test'
Requires-Dist: pytest-black ; extra == 'test'
Requires-Dist: pytest-isort (>=1.1.0) ; extra == 'test'
Requires-Dist: pytest-mypy ; extra == 'test'
```
and in [darker-1.0.0.tar.gz](https://files.pythonhosted.org/packages/7a/48/e0ce70e5a2774d87fd6e5fbe5f548c62dbbe33c78f4e2c8f469f77bf858a/darker-1.0.0.tar.gz):
```ini
$ tar xOf darker-1.0.0.tar.gz darker-1.0.0/setup.cfg | grep -A3 install_requires
install_requires = 
	black
	typing-extensions ; python_version < "3.8"
python_requires = >=3.6

$ tar xOf darker-1.0.0.tar.gz darker-1.0.0/src/darker.egg-info/requires.txt                    
black

[:python_version < "3.8"]
typing-extensions

[isort]
isort>=5.0.1

[test]
pytest
pytest-black
pytest-isort>=1.1.0
pytest-mypy
```

**Comment by akaihola** [comment]
So @CircleOnCircles is this a Poetry bug (python-poetry/poetry#2687?) or can we do something in Darker to fix this problem?

**Comment by CircleOnCircles** [comment]
Yes, I guess.
At first, I thought we might be able to do a hotfix like specify the version. I had tried to explore the source code related to version dep. I came to the same conclusion as you.
