### ISSUE TITLE
black.InvalidInput: Cannot parse: 1:0: ﻿#pylint: disable when its the first line in the file

### ISSUE THREAD

**Issue by markddavidoff** [akaihola/darker#63]
Getting the following error trying to run darker on a bunch of files when a git revision is specified with -r

black.InvalidInput: Cannot parse: 1:0: ﻿#pylint: disable=missing-docstring, invalid-name, too-few-public-methods, too-many-lines

to : darker -r <revision> filepath

when the first line in the file is `#pylint: disable=missing-docstring, invalid-name, too-few-public-methods, too-many-lines`

**Comment by markddavidoff** [comment]
actually looking into it more, after removing that line, it still seems to error out, perhaps its the line in the revision?

**Comment by akaihola** [comment]
Thanks @markddavidoff,
```
black.InvalidInput: Cannot parse: 1:0: ﻿#pylint: disable=missing-docstring, invalid-name, too-few-public-methods, too-many-lines
```
doesn't look like an error from Darker itself, but from Black.

Do you think you could come up with a minimal example to reproduce this?

Also, what was the error when you removed the first line in the file?

What about if you use a different Black version?

**Comment by markddavidoff** [comment]
can't repro anymore, lets close this.
