### ISSUE TITLE
Vscode instructions don't work on OSX

### ISSUE THREAD

**Issue by virtuald** [akaihola/darker#67]
* VSCode 1.48.2
* Darker 1.1.0
* Black 20.8b1
* Python 3.7.3
* Python extension 2020.8.105045

Workspace settings:

```
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/home/virtuald/.virtualenvs/frc-2020/bin/darker",
    "python.formatting.blackArgs": [
        "--diff"
    ],
    "editor.formatOnSave": true,
```

In the output section it does look like it's running darker, but nothing happens (and there's an extra diff -- I tried removing it and it didn't fix it):

```
> ~/.virtualenvs/frc-2020/bin/darker --diff --diff --quiet ~/dev/frc/test/test.py.5653cc201affb899ab4952d1f891988b.tmp
cwd: ~/dev/frc/test
```

Changing the formatter to the original black executable does formatting as one would expect.

**Comment by akaihola** [comment]
@Carreau could you look at this issue – is there an incompatibility or a mistake in our instructions?

Maybe `darker` doesn't like the fact that the file name ends with `.tmp` instead of `.py`?

**Comment by shangxiao** [comment]
I noticed this issue as well… but only for files that you open "directly".  If you open a folder, then open a file it works. Forgive me as I'm not a VS Code user but I just wanted to report that it does indeed 1/2 work.

I examined the output of `darker --diff` vs `black --diff` and I wonder whether it's because black seems to report the patch with absolute paths whereas darker used relative paths? 🤔

**Comment by akaihola** [comment]
> black seems to report the patch with absolute paths whereas darker used relative paths

@shangxiao if I create a branch which changes Darker to report absolute paths, would you be willing to test it with VS Code?

**Comment by akaihola** [comment]
> I examined the output of `darker --diff` vs `black --diff` and I wonder whether it's because black seems to report the patch with absolute paths

@shangxiao I tried `black --diff` with Black 20.8b1, and I see only relative paths. Do you have a different version?

**Comment by akaihola** [comment]
@shangxiao other differences between Black and Darker `--diff` output:
- Black displays five lines of context, Darker only three
- Black includes file modification timestamps on the `---` and `+++` lines, Darker doesn't

Those I could also try enabling in a branch so they could be tested with VS Code.

**Comment by akaihola** [comment]
@virtuald @shangxiao @Carreau you could try whether #84 makes any difference for VS Code.

**Comment by akaihola** [comment]
I wonder if this is the same issue as #104, and whether it still happens with Darker 1.3.0.
