### ISSUE TITLE
darker.verification.NotEquivalentError: nonascii2.py (IPython test file)

### ISSUE THREAD

**Issue by Carreau** [akaihola/darker#768]
(**update:** the issue is in Darkgraylib, see akaihola/darkgraylib#86)

---

**Describe the bug**

Consider the following file – which is a weird encoding test code file of IPython reduce to it's minimal form:

```
# coding: iso-8859-5
# хц
```

(more precisely, `b'# coding: iso-8859-5\n# \xd1\x85\xd1\x86\n'`)

running darker on this file; fails with `darker.verification.NotEquivalentError: nonascii2.py`

**To Reproduce**

1. Clone this repository: '...' (or e.g. commit these files in a new local Git repository: '...')
2. In a fresh virtualenv, `pip install darker==2.1.1` (or main)
3. Run Darker with `darker nonascii2.py`
4. See NotEquivalentError

**Expected behavior**
don't modify file; it should be good.

**Environment (please complete the following information):**
 - OS: macos
 - Python version 3.12.3
 - Git version ed005fa0989192161f63ad92d728d36cf7d32aff
 - Darker version 2.1.1
 - Black version 24.10

**Additional context**

From some debug in is_equivalent_to_baseline

```
baseline:'# coding: iso-8859-5\n# б\x85б\x86\n'
reformat:'# coding: iso-8859-5\n# б\nб\x86\n',
```

Note that this is likely a weird edge case, I'm quite certain that something is wonky is going on with encoding as despite the `# coding:` comment the file is likely utf-8 as 
```
>>> b'\xe5\xe6'.decode('iso-8859-5') == 'хц'
```
but
```
>>> b'\xd1\x85\xd1\x86'.decode('utf-8') == 'хц'
```

The file is encoded utf-8, but the code comment says, `iso-8859-5`, 

regardeless darker did a `NotEquivalentError`, so maybe it will help find an edgecase.

**Comment by akaihola** [comment]
Thanks @Carreau, I'll need to refresh my memory on how Darker deals with encodings. I'll also check whether the behavior is the same on different platforms.

**Comment by Carreau** [comment]
No worries, I think it's an extremely rare edge case, and it is likely that the bug is due to a file that was used in Python2 times, but not relevant now anymore; so no hurry.

**Comment by akaihola** [comment]
@Carreau, the core of the issue is this:
```python
>>> "a\x85b".splitlines()
['a', 'b']
```

**Comment by akaihola** [comment]
...and indeed Python documentation for [str.splitlines] says:

>`str.splitlines(_keepends\=False_)`
>
>Return a list of the lines in the string, breaking at line boundaries. Line breaks are not included in the resulting list unless _keepends_ is given and true.
>
>This method splits on the following line boundaries. In particular, the boundaries are a superset of [universal newlines].
>
>| Representation | Description |
>| --- | --- |
>| `\n` | Line Feed |
>| `\r` | Carriage Return |
>| `\r\n` | Carriage Return + Line Feed |
>| `\v` or `\x0b` | Line Tabulation |
>| `\f` or `\x0c` | Form Feed |
>| `\x1c` | File Separator |
>| `\x1d` | Group Separator |
>| `\x1e` | Record Separator |
>| _**`\x85`**_ | _**Next Line (C1 Control Code)**_ |
>| `\u2028` | Line Separator |
>| `\u2029` | Paragraph Separator |

[str.splitlines]: https://docs.python.org/3/library/stdtypes.html#str.splitlines
[universal newlines]: https://docs.python.org/3/glossary.html#term-universal-newlines

**Comment by akaihola** [comment]
@Carreau, I created akaihola/darkgraylib#86 for this issue.
